### ISSUE TITLE
Unreliable behaviour

### ISSUE THREAD

**Issue by hamoid** [okgrow/iron-router-autoscroll#5] opened 2015-03-19 12:14 UTC
It does not seem to work for me.
1. I open http://l:3000/object/HZgaRmRePoxqfxA42, scroll down, click a link to http://l:3000/object/HZgaRmRePoxqfxA42/edit/material and scrolls up. Expected. 
2. But now I click the back button and the scroll stays on top instead of pulling the original scroll value. Unexpected.
3. I scroll down again as I did on point 1, and click the same link again. No longer scrolls to top, it scrolls up a few pixels. Unexpected.

Any idea how to fix it?

**Comment by pauldowman** [comment] 2015-04-21 14:43
I can't reproduce this. Can you give me a link to your app or a MeteorPad or something that exhibits the issue?

**Comment by pauldowman** [comment] 2015-04-23 12:41
@hamoid I'm closing this for now but feel free to re-open it if you can confirm that it's a bug, and either way I can try to help you get it working.

**Closed as completed by pauldowman** 2015-04-23 12:41 UTC
Labels: can't reproduce

**Comment by hamoid** [comment] 2015-04-23 18:39
Hi, sorry I didn't give more details. I implemented a simple scroll to top. I'll post more details if I get time to try again.

**Comment by pauldowman** [comment] 2015-04-24 02:05
No problem, thanks for reporting it. But I'm pretty sure this package should be able to work for you. Also note that a recent update fixed a FireFox bug.
